name: commitlint
on:
  pull_request:
permissions:
  contents: read
jobs:
  commitlint:
    permissions:
      contents: read
    uses: unabandoned/.github/.github/workflows/reusable-commitlint.yml@14773d61b24fecaea9b2077caf54104cf46c3932 # main
