name: publish
on:
  release:
    types: [published]
permissions:
  contents: read
  id-token: write   # required for OIDC on the calling job
jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: unabandoned/.github/.github/workflows/reusable-publish.yml@14773d61b24fecaea9b2077caf54104cf46c3932 # main
    with:
      install-for-publish: false
    secrets: inherit
