name: release-please
on:
  push:
    branches: [master]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: unabandoned/.github/.github/workflows/reusable-release-please.yml@14773d61b24fecaea9b2077caf54104cf46c3932 # main
    secrets: inherit
