name: release-please
on:
  push:
    branches: [master]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: unabandoned/.github/.github/workflows/reusable-release-please.yml@0c6624ebbfd7e7f93a448163c241111768d86541 # main
    secrets: inherit
